引用投稿に対応
4m-mazi/fixup-twitter-link pull request #98
Opened 2023-11-09 10:53 UTC by Mogyuchi

close #92

2023-11-10 14:45 UTC, hulk510 commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
ios用のスペースは必要なくなった？

2023-11-10 14:50 UTC, hulk510 requested changes

2023-11-10 14:50 UTC, hulk510 commented on src/createEmbeds.ts
> +const createDescriptin = (tweet: APITweet): string => {
```suggestion
const createDescription = (tweet: APITweet): string => {
```
o抜けてない？

2023-11-10 14:55 UTC, Mogyuchi commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
ツイート著者名のほうを押せるので問題ない

2023-11-10 14:59 UTC, hulk510 commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
```
description: tweet.text + `\n\n[<t:${tweet.created_timestamp}:R>        ](${tweet.url})`, // モバイル版でタップする領域を確保するためにスペースが必要
```
この修正自体消えたってこと？

2023-11-10 15:13 UTC, Mogyuchi commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
それ違う行

2023-11-10 15:44 UTC, hulk510 commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
あーコンフリクトしてるだけで追加されてないだけか。

2023-11-10 15:48 UTC, Mogyuchi commented on src/createEmbeds.ts
> +        `[${tweet.quote.author.name}(@${tweet.quote.author.screen_name}) <t:${tweet.quote.created_timestamp}:R>](${tweet.quote.url})`,
あと、14行目の話だわ
別PRでやったことなので入れてなかった

2023-11-10 16:12 UTC, hulk510 submitted a review, later dismissed

2023-11-20 04:58 UTC, hulk510 approved these changes
jsonで取得するのいいね
どうもですー！

2023-11-20 04:58 UTC, merged